# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       nemo-qml-plugin-folderlistmodel

# >> macros
# << macros

Summary:    Folder list model plugin for Nemo Mobile
Version:    0.0.0
Release:    1
Group:      System/Libraries
License:    BSD
URL:        https://github.com/nemomobile/nemo-qml-plugin-folderlistmodel
Source0:    %{name}-%{version}.tar.bz2
Source100:  nemo-qml-plugin-folderlistmodel.yaml
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
Provides:   nemo-qml-plugins-folderlistmodel > 0.3.5
Obsoletes:   nemo-qml-plugins-folderlistmodel <= 0.3.5

%description
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_libdir}/qt5/qml/org/nemomobile/folderlistmodel/libnemofolderlistmodel.so
%{_libdir}/qt5/qml/org/nemomobile/folderlistmodel/qmldir
# >> files
# << files
