# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       nemo-qml-plugin-folderlistmodel

# >> macros
# << macros

Summary:    Folder list model plugin for Nemo Mobile
Version:    0.0.0
Release:    1
Group:      System/Libraries
License:    BSD
URL:        https://github.com/nemomobile/nemo-qml-plugin-folderlistmodel
Source0:    %{name}-%{version}.tar.bz2
Source100:  nemo-qml-plugin-folderlistmodel.yaml
BuildRequires:  pkgconfig(QtCore) >= 4.7.0
BuildRequires:  pkgconfig(QtDeclarative)

%description
%{summary}.

%package folderlistmodel
Summary:    Folder list model for QML applications
Group:      System/Libraries

%description folderlistmodel
A model providing a view of the filesystem for QML applications


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post


%files folderlistmodel
%defattr(-,root,root,-)
%{_libdir}/qt4/imports/org/nemomobile/folderlistmodel/libnemofolderlistmodel.so
%{_libdir}/qt4/imports/org/nemomobile/folderlistmodel/qmldir
# >> files folderlistmodel
# << files folderlistmodel
